# Use the official Rust image as a base image
FROM rust:latest

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    librust-alsa-sys-dev \
    libudev-dev \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /usr/src/cloud_glimpse

# Copy the entire project directory into the container
COPY . .

# Build the project
RUN cargo build --release

# Expose any necessary ports
EXPOSE 8000

# Command to run your application
CMD ["python3", "serve.py"]
